setup /i PATH=PATH FILE=FILE PATHUSER=PATHUSER PATHPASSWORD=PATHPASSWORD EXECUSER=EXECUSER EXECPASSWORD=EXECPASSWORD PARAMETERS=PARAMETERS SILENT=NO
SCRIPTVARNAME1=TOMEK SCRIPTVARVALUE1=EXAMPLEVARIALBE


